name: Lint Code Base

on: [push, pull_request]

jobs:
  lint:
    name: MegaLinter Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: MegaLinter Terraform
        uses: oxsecurity/megalinter/flavors/terraform@v7
